name: "celeba-hat-r50"

model:
  class_name: "classifier.ResnetClassifierModule"
  backbone: "r50"
  pretrained: true
  num_classes: 1
  multilabel: true
  optimizer_config:
    method: "Adam"
    params:
      lr: 0.0001
  scheduler_config: null


datamodule:
  class_name: "data.celeba.CelebADataModule"
  data_dir: "/scratch/shared"
  attr_names: ["Wearing_Hat"]
  batch_size: 64
  num_workers: 5
  pin_memory: true


trainer:
  max_epochs: 20


checkpoint:
  every_n_epochs: 5
  save_last: true

