model:
  class_name: "classifer.ResnetClassifierModule"
  params:
      num_classes: 2
      num_channels: 3
      dropout_rate: 0.2
      weight_decay: 0.0001
      learning_rate: 0.001
      batch_size: 32
      num_epochs: 10
      num_workers: 4
      data_dir: "data/celeba"
      checkpoint_dir: "checkpoints/celeba"
  log_dir: "logs/celeba"
    device: "cuda:0"
      seed: 42